version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:12
      - image: trufflesuite/ganache-cli
        command: ganache-cli --deterministic
    steps:
      - checkout
      - Migrate Contracts
        - steps:
            - cd truffle
            - truffle console --circleci
            - truffle migrate
            - .exit
      - Test frontend
        - steps: 
            - yarn
            - yarn test

