version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:12
      - image: trufflesuite/ganache-cli
        command: ganache-cli --deterministic
    steps:
      - checkout
      - run:
        name: Migrate Contracts
        command: 'cd truffle'
        command: 'truffle console --circleci'
        command: 'truffle migrate'
        command: '.exit' 
      - rund:
        name: Test frontend
        command: 'cd ../react-app'
        command: 'yarn && yarn test'
